language: node_js
os:
  - osx
  - linux
node_js: 14

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - |
    echo ">>> Installing dependencies"
    yarn
    echo ">>> Run integration test"
    yarn test
cache: yarn